### ISSUE TITLE
Providing an example project

### ISSUE THREAD

**Issue by paulwehner** [odysseyscience/react-router-proxy-loader#7]
Hey, any chance you could provide an example project that shows this loader being used in conjunction with jsx-loader and style-loader?

**Comment by seanadkinson** [comment]
Hmmm, I could probably add more to the README, but the `react-router-proxy` stuff only affects the including of `Route` components.  Everything else in a working `react-router` project is the same as without using this code.  That is, any examples you can find on the internet using `jsx-loader` and `style-loader` would work exactly the same with or without using `react-router-proxy-loader`.  Does that make sense?

The existing example in README is really the only change needed to use this loader.  Perhaps you can be more specific about what you would hope to gain with a more full example, since it really would just be a boilerplate webpack app example.

**Comment by paulwehner** [comment]
I'd be helpful to see ho the webpack.config.js file would need to be updated, if at all.  So for example how would the following loaders section need to be updated?

```
loaders: [
      { test: /\.js$/, loader: 'jsx-loader?harmony' },
      { test: /\.less$/, loader: 'style-loader!css-loader!less-loader' },
      { test: /\.css$/, loader: 'style-loader!css-loader' },
      { test: /\.(png|jpg)$/, loader: 'url-loader?limit=8192' }
]
```

**Comment by seanadkinson** [comment]
It wouldn't need to be updated at all actually.  I'd just put the loaders inline like it shows in the `README`: https://github.com/odysseyscience/react-router-proxy-loader#named-chunks-021-and-above

Someone creating an isomorphic application may not be able to put them in the `routes` file, but I haven't dug into how exactly they should be specified in the webpack config yet.  If you come up with something that works for you, please let me know and I can update the README with some guidance.

**Comment by seanadkinson** [comment]
I'd imagine that you would have to come up with a regex that will catch all the components that you want lazy-loaded, but it seems dangerous, since it may not be obvious what is going on, and you may catch components that you don't want lazy-loaded.

But let's say everything in `app/pages` should be lazy-loaded, then maybe something like:

```
loaders: [
    { test: /\/app\/pages\/.*/, loader: 'react-router-proxy' }
]
```

**Comment by seanadkinson** [comment]
As mentioned, seems like the README pretty much says everything this repo does, so I'll close for now.
