### ISSUE TITLE
Support server-side rendering

### ISSUE THREAD

**Issue by necolas** [odysseyscience/react-router-proxy-loader#8]
Probably want something like this: https://github.com/webpack/react-proxy-loader/blob/master/unavailable.js

**Comment by seanadkinson** [comment]
I haven't looked deeply into getting server-side rendering working, but I believe that any webpack-specific loader syntax isn't going to work for requiring module from node.

So anything like:

```
require('react-proxy-loader!module.jsx
```

Will never work when run server-side, right?

If that's true, then the only way to make your routes isomorphic would be to do some webpack-specific configuration that maybe aliases the component to include `react-router-proxy-loader`.

Again, haven't given server-side rendering much thought, so I hope if you are looking into it, you can provide some insight.

How does `unavailable.js` address the issue of server-side rendering, though?

**Comment by necolas** [comment]
webpack supports building for a node environment. you can alias the proxy loader to `react-proxy-loader/unavailable` in your node-targeting webpack config. see: https://github.com/webpack/react-starter/blob/c9567168cf7899a8c8292b531234a49983daa51d/make-webpack-config.js#L76-L77

**Comment by necolas** [comment]
I opened an issue on react-proxy-loader to get more related info: https://github.com/webpack/react-proxy-loader/issues/13. It sounds like you should be able to support generate bundles for node environments, but not prerendering the route.

**Comment by seanadkinson** [comment]
Oh, I see.  So if you use webpack to produce a build artifact, then you could include that artifact in a node environment without stuff breaking, but it wouldn't actually be able to render anything.

I think most users of `react-router-proxy-loader` would simply want to be able to require their Routes file server-side without having the additional build step of producing a compatible artifact.  Hopefully we can come up with a solution to allow that to be simple.

We may be looking at server-side rendering soon at work, at which point I'll be able to give this more thought.

Thanks for pointing out the node-specific build though.

**Comment by seanadkinson** [comment]
Latest comment from @jregeimbal [here](https://github.com/petehunt/webpack-howto/issues/18#issuecomment-99175354) shed some light on some of the potential issues with server-side rendering.  Namely, the component structure is different on the server than it would be on the client, because on the client, we render a proxy component that houses the asynchronously loaded component.

So on the client, you might have:

```
Application
  |- ReactProxy
    |- UserDetails
```

Where `Application` is some base component, and `UserDetails` is a lazy-loaded component using `react-router-proxy-loader`.

On the server, if we did this the way it seems like it should be done, you would ideally have:

```
Application
  |- UserDetails
```

This is possible because you don't need the `ReactProxy` component on the server, since you can just load up `UserDetails` right away.

However, as @jregeimbal pointed out, this doesn't work when React re-binds the component tree client-side, since the structure is expected to be the same, and it is missing the proxy component.

The only way I see to make this work would then be to render the `ReactProxy` component server-side, but immediately render `UserDetails` as well.

So the question now becomes: How can we render `ReactProxy` and `UserDetails` server-side, but still load things asynchronously client-side?

**Comment by jregeimbal** [comment]
Hi All, @seanadkinson thanks for the help and thoughts.  I realized after understanding your solution and a bit of digging that it was pretty trivial to emulate ReaxtProxy and avoid the async piece, so I created a component that is simply missing the require.ensure to use in Node:

```
var React = require("react");
var mixinReactProxy = require("./mixinReactProxy.react");
var component;
var desc = {
  loadComponent: function(callback) {
    if(!component) {
      component = require( this.props.moduleRequest );
      if(callback) callback(component);
    }
    return component;
  }
};
mixinReactProxy(React, desc);
module.exports = React.createClass(desc);
module.exports.Mixin = desc;
```

However, this did not satisfy react which still encountered a checksum mismatch.

As it turns out, on the client side react ReactProxy renders a noscript tag while waiting for the async request to complete, and this appears to using this place holder as it calculates a checksum before the lazy loaded component resolves.

```
<noscript data-reactid=".1izxho6u96o.1.0.1.0"></noscript>
```

I think the only solution is to find a way in ReactProxy to have React avoid comparing the pre-rendered inner HTML with the client side react virtual Dom (again just inside the component, for example "main" above, until the async request completes and the received component renders.

Imagine a scenario with nested lazy loaded components, React should avoid a checksum comparison until all request complete and are rendered to the virtual dom.

**Comment by seanadkinson** [comment]
Hmmm,  I wouldn't expect React to be comparing the DOM until the `React.render` is called, and this should happen after the Route is loaded and ready to render, no?

```
Router.run(routes, function(Handler) {
  React.render(<Handler/>, document.body);
});
```

Won't React wait until trying to render `Handler` before comparing DOM?  It would have to, really, because before calling `React.render(<Handler/>)`, you haven't told React to do anything yet.

The `react-router-proxy-loader` shouldn't be rendering a `<noscript/>`, since by the time `Handler` is returned in the function above, I'd expect all the `willTransitionTo` calls to have already been made, and therefore all the scripts and components loaded.  But clearly I could be mistaken.

Do you have a sample project that you are working on that you could put up somewhere?  I haven't actually tried to get server-side rendering working, so all my comments are simply from thinking about things, not actually trying things out :-)

**Comment by necolas** [comment]
I don't follow where the confusion lies. This is already solved in react-proxy-loader. For node targets you configure webpack to use the 'unavailable' version of loader instead (which is effectively a no-op). No need to duplicate all your routes in a server module.

Sounds like react-router 1.0 will make async loading of route components much easier.

**Comment by seanadkinson** [comment]
Confusion lies in trying to get the components rendered server side synchronously, and client side asynchronously. That is, if rendering on the server, we should ideally be able to load the entire route hierarchy and deliver that to the client fully rendered. On client side, it should still lazy-load pages that aren't rendered.

If we just replace react-router-proxy-loader with an Unavailable component on the server, that would take away the benefits of server-side rendering, since the client would still need to make one or more server calls to download javascript, and then would still render some or all of the page client side.

Hope that helps clear up the confusion, and clarifies what we are trying to accomplish on the server.

**Comment by necolas** [comment]
The server should render the same thing as the client initially expects. So async routes should not be rendered on the server. What you suggested is much more complicated, as mentioned by Tobias here: https://github.com/webpack/react-proxy-loader/issues/13.

It's an optimization rather than a blocker to getting this working for "isomorphic" architectures.

**Comment by seanadkinson** [comment]
That's a good point.  I'll see if we can start there and enhance later.  PRs welcome, since I may not get to this for a little while.

**Comment by livtanong** [comment]
I've tried prerendering a project using this, and I'm getting a "window is not defined" error. Moving forward, I suggest avoiding using document and window for this if you are going to support server-side prerendering.

**Comment by matthewoden** [comment]
So, I found a way to get prerendering working with react proxy loader, webpack, and node. Here's a very basic example, showing how I set up my server rendering, webpack, and routes:

https://gist.github.com/matthewoden/0ef78e5dc6ee04b6aa1e

ah crap, just realized this is react-router-proxy-loader. Well... It kind of still applies? kind of?

**Comment by mariopeixoto** [comment]
It seems to me that the problem is the first render that runs on the client returns null since the routes are not loaded yet. React will then build the noscript tag as mentioned above, React proxy then plug the load callback into the componentDidMount, and when the load is done, the callback is called, the state is set, and it triggers an update. 

I find the idea of not rendering async routes on the server fundamentally wrong. The perfect behavior would be to render a route on the server, send the full html back to the user so he can have a nice 'server app experience' on the first load, and still be able to load the other routes asynchronously but I don't how to achieve that right now...
